# Pandas Cheat Sheet

## 1. Importing and Exporting Data
```python
import pandas as pd

# Read data
df = pd.read_csv("file.csv")       # Read CSV file
df = pd.read_excel("file.xlsx")    # Read Excel file
df = pd.read_json("file.json")     # Read JSON file
df = pd.read_sql(query, con)	   #Read SQL query or database table into a DataFrame.

# Write data
df.to_csv("file.csv")              # Write DataFrame to CSV
df.to_excel("file.xlsx")           # Write DataFrame to Excel
df.to_json("file.json")            # Write DataFrame to JSON
```

## 2. Creating DataFrames
```python
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)            # Create DataFrame
s = pd.Series([1, 2, 3])           # Create Series
df = pd.concat([df1, df2])	       #Concatenate DataFrames vertically or horizontally.
df = pd.merge(df1, df2, on='key')  #Merge DataFrames on a key column.
pivot = pd.pivot_table(df, ...)	   #Create a pivot table.
```

## 3. Viewing and Inspecting Data
```python
df.head()                          # First 5 rows
df.tail()                          # Last 5 rows
df.info()                          # Summary of the DataFrame
df.describe()                      # Statistics of numerical columns
df.shape                           # Shape of the DataFrame
df.columns                         # List of column names
df.dtypes                          # Data types of columns
df.sample(5)                       # Random 5 rows
```

## 4. Selecting and Filtering Data
```python
df['column']	              #Select a single column.
df[['col1', 'col2']]	      #Select multiple columns.
df.iloc[row, col]	        #Select rows/columns by index positions.
df.loc[row, col]	        #Select rows/columns by labels.
df[df['column'] > value]	#Filter rows by condition.
df.query('column > value')	#Query rows based on conditions.
df.mean()	                #Compute mean of columns.
df.median()	                #Compute median of columns.
df.sum()	                #Compute column-wise or row-wise sum.
df.min()	                #Minimum values in columns.
df.max()	                #Maximum values in columns.
df.count()	                #Count non-missing values in each column.
df.groupby('column')	    #Group data by a column.
df.agg({'col1': 'mean', 'col2': 'sum'})	#Apply multiple aggregation functions.
```

## 5. Sorting and Ranking
```python
df.sort_values(by='column')        # Sort by column
df.sort_values(by='column', ascending=False)  # Descending sort
df.rank()                          # Rank values
```

## 6. Handling Missing Data
```python
df.isnull()	        #Detect missing values.
df.notnull()	    #Detect non-missing values.
df.dropna()	        #Drop rows with missing values.
df.fillna(value)	#Fill missing values with value.
df.interpolate()	#Fill missing values using interpolation.
```

## 7. Aggregations and Grouping
```python
df.mean()	#Compute mean of columns.
df.median()	#Compute median of columns.
df.sum()	#Compute column-wise or row-wise sum.
df.min()	#Minimum values in columns.
df.max()	#Maximum values in columns.
df.count()	#Count non-missing values in each column.
df.groupby('column')	#Group data by a column.
df.agg({'col1': 'mean', 'col2': 'sum'})	#Apply multiple aggregation functions.
df['column'].mean()                # Mean of a column
df.groupby('group').sum()          # Group by and aggregate
df.agg({'col1': 'mean', 'col2': 'sum'})  # Multiple aggregations
```

## 8. String Operations
```python
df['col'].str.lower()              # Lowercase strings
df['col'].str.upper()	           #Convert strings to uppercase.
df['col'].str.strip()	           #Remove leading and trailing spaces.
df['col'].str.contains('text')     # Check if contains substring
df['col'].str.replace('old', 'new')  # Replace substring
```

## 9. Reshaping Data
```python
df.melt(id_vars=['id'])            # Convert wide to long format
df.pivot(index='index', columns='col', values='val')  # Long to wide
df.stack()	                       #Stack columns into rows.
df.unstack()	                   #Unstack rows into columns.
```

## 10. Time Series
```python
df['date'] = pd.to_datetime(df['date'])  # Convert to datetime
df['year'] = df['date'].dt.year          # Extract year
df['month'] = df['date'].dt.month        # Extract month
df.resample('M').mean()                  # Resample by month
df.resample('M').mean()	                 #Resample time series data (e.g., monthly).
```

## 11. Joining and Merging
```python
pd.merge(df1, df2, on='key')            # Merge DataFrames
pd.concat([df1, df2])                   # Concatenate DataFrames
df1.join(df2, on='key')                 # Join DataFrames
```

## 12. Advanced Functions
```python
df.apply(func)                         # Apply function to rows or columns
df.map(func)                           # Apply function to Series
df.transform(func)                     # Transform data
df.pivot_table(values='val', index='id', columns='col', aggfunc='mean')  # Pivot table
```

# Steps

## 1. Import pandas

In [3]:

import pandas as pd

## 2. Read and save dataset

In [4]:
df=pd.read_csv("datasets/dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

## 3. Inspect the dataset

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [4]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

> Conclusion:
1. Transaction ID has no Null or NaN or Empty Values
2. Item, Quantity, Price Per Unite, Total Spent, Payment Method, Location, Transaction Date all have Null Values
3. All the columns are of the type object which we need to fix

## 4. Deal with empty values

First let's deal with the empty values in the Item Column, since we have a "Price Per Unit" we can deduce what item that was

In [6]:
#let's make a price dict
item_price = {
    'Coffee': 2.0,
    'Tea': 1.5,
    'Sandwich': 4.0,
    'Salad': 3.0,
    'Cake': 3.0,
    'Cookie': 1.0,
    'Smoothie': 4.0,
    'Juice': 3.0
}

# Reverse mapping (price to item)
price_item = {price: item for item, price in item_price.items()}

print(item_price)
print(price_item)

{'Coffee': 2.0, 'Tea': 1.5, 'Sandwich': 4.0, 'Salad': 3.0, 'Cake': 3.0, 'Cookie': 1.0, 'Smoothie': 4.0, 'Juice': 3.0}
{2.0: 'Coffee', 1.5: 'Tea', 4.0: 'Smoothie', 3.0: 'Juice', 1.0: 'Cookie'}

In [9]:
try:
    df['Price Per Unit']=df['Price Per Unit'].astype(float)
except Exception as e:
    print(e)
    pass

could not convert string to float: 'ERROR'

### 1. Detect Null values

In [10]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [11]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### 2. Convert strings to Null values

Can't perform _fillna()_ if NA is a string

```python
numpy.replace([x, y], np.nan)
```

In [12]:
import numpy as np
df['Price Per Unit'] = df['Price Per Unit'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Price Per Unit'] = df['Price Per Unit'].astype(float)
df["Price Per Unit"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: Price Per Unit
Non-Null Count  Dtype
--------------  -----
9467 non-null   float64
dtypes: float64(1)
memory usage: 78.3 KB

In [13]:
df['Item'] = df['Item'].fillna(df['Price Per Unit'].map(price_item))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9939 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(1), object(7)
memory usage: 625.1+ KB

#### Converting Total Spent

In [14]:
df['Total Spent'] = df['Total Spent'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Total Spent'] = df['Total Spent'].astype(float)

#### Converting Quantity

In [15]:
df['Quantity'] = df['Quantity'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Quantity']=df['Quantity'].astype(float)

### 3. Filling NA values

In [16]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9939 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

#### Fillna _Item_ column

In [17]:
df['Item'] = df['Item'].fillna(df['Price Per Unit'].map(price_item))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9960 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

### 4. Drop NA rows

If remaining NA values don't make sense

In [18]:
df.dropna(subset=['Item'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9960 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9960 non-null   object
 1   Item              9960 non-null   object
 2   Quantity          9484 non-null   float64
 3   Price Per Unit    9924 non-null   float64
 4   Total Spent       9460 non-null   float64
 5   Payment Method    7391 non-null   object
 6   Location          6712 non-null   object
 7   Transaction Date  9801 non-null   object
dtypes: float64(3), object(5)
memory usage: 700.3+ KB

#### Dropping _Transaction Date_ NA rows

In [19]:
df.dropna(subset=['Transaction Date'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9801 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9801 non-null   object
 1   Item              9801 non-null   object
 2   Quantity          9334 non-null   float64
 3   Price Per Unit    9767 non-null   float64
 4   Total Spent       9310 non-null   float64
 5   Payment Method    7280 non-null   object
 6   Location          6607 non-null   object
 7   Transaction Date  9801 non-null   object
dtypes: float64(3), object(5)
memory usage: 689.1+ KB